name: Python code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pythonexecution:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run Python Script
      run: |
        python3 abc.py
